spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  #  delete, put 메소드 사용
  mvc:
    hiddenmethod:
      filter:
        enabled: true